### ISSUE TITLE
database is locked

### ISSUE THREAD

**Issue by bolianlai** [storyicon/golang-proxy#4]
使用默认sqlite数据库，使用api经常出现这个，是不是数据库读写太频繁导致锁的问题？
使用读写分离能不能解决这个问题？
`{
error: "database is locked",
message: [ ]
}`

**Comment by storyicon** [comment]
Really, but I have no plans to do these on this small project yet.

**Comment by storyicon** [comment]
But according to the assessment, using mysql as the database will be much better.
https://github.com/storyicon/golang-proxy/tree/master/config
